version: "3.1"
services:
  web:
    image: odoo_15:${ODOO_VERSION}
    depends_on:
      - db
    ports:
      - "${ODOO_PORT}:${ODOO_PORT}"
      - "${DEBUGPY_PORT}:${DEBUGPY_PORT}"
    volumes:
      - ./conf:/etc/odoo
      - odoo-web-data:/var/lib/odoo
      - ${ODOO_SERVER}:/var/lib/odoo/odoo
      - ${ENTERPRISE}:/var/lib/odoo/enterprise
      - ${ADDONS}:/var/lib/odoo/custom-addons
      - ${DEPLOGV15}:/var/lib/odoo/deplogv15
    entrypoint: ${ENTRYPOINT}
  db:
    image: postgres:${PG_VERSION}
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
