version: "3.1"
services:
    web:    
        container_name: ${ODOO_CONTAINER_NAME}
        image: odoo15:${ODOO_VERSION}
        depends_on:
        - db
        ports:
        - "${ODOO_PORT}:${ODOO_PORT}"
        - "${DEBUGPY_PORT}:${DEBUGPY_PORT}"
        volumes:
        - ./conf:/etc/odoo
        - odoo-web-data:/var/lib/odoo
        - ${ODOO_SERVER}:/var/lib/odoo/odoo
        - ${ENTERPRISE}:/var/lib/odoo/enterprise
        - ${CUSTOM_ADDONS}:/var/lib/odoo/custom-addons
        - ${DEPLOGV15}:/var/lib/odoo/deplogv15
        entrypoint: ${ENTRYPOINT}
    db:
        container_name: ${PG_CONTAINER_NAME}
        image: postgres:${PG_VERSION}
        environment:
        - POSTGRES_DB=postgres
        - POSTGRES_PASSWORD=${PG_PASSWORD}
        - POSTGRES_USER=${PG_USER}
        - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
        - '${PG_PORT}:5432'
        volumes:
        - odoo-db-data:/var/lib/postgresql/data/pgdata
    pgadmin:
        container_name: ${PGADMIN_CONTAINER_NAME}
        image: ${PGADMIN_VERSION}
        depends_on: 
            - db
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        ports:
            - "${PGADMIN_PORT}:80"
volumes:
    odoo-web-data:
    odoo-db-data:

